# Generated by Django 5.0.2 on 2024-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Field1", models.CharField(max_length=100)),
                ("Field2", models.CharField(max_length=100)),
                ("Field3", models.CharField(max_length=100)),
                ("Field4", models.CharField(max_length=100)),
                ("Field5", models.CharField(max_length=100)),
                ("Field6", models.CharField(max_length=100)),
                ("Field7", models.CharField(max_length=250)),
            ],
        ),
    ]
