# Generated by Django 5.0.2 on 2024-02-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraping", "0002_category_product_website_delete_article_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("products_count", models.IntegerField(default=0)),
                ("products_created", models.IntegerField(default=0)),
                ("products_updated", models.IntegerField(default=0)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraper_runs",
                        to="Scraping.website",
                    ),
                ),
            ],
        ),
    ]
